# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - stage

pool:
  name: Cool Pool

steps:
  - checkout: self
    persistCredentials: true
  - task: NodeTool@0
    displayName: Node version task
    inputs:
      versionSpec: '16.13.1'

  - task: Bash@3
    displayName: Build theme assets
    inputs:
      targetType: inline
      script: |

        # Change dir
        cd ./wp-content/themes/ew-theme

        # Install yarn
        yarn install

        # Build assets
        yarn build

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |

        # Clear root files
        rm -rf ./wp-config.php
        rm -rf ./.git
        rm -rf ./documentation
        rm -rf ./.gitignore
        rm -rf ./.gitattributes
        rm -rf ./azure-pipelines.yml
        rm -rf ./*.bat
        rm -rf ./*.sh
        rm -rf ./*.md
        rm -rf ./*.phar
        rm -rf ./*.json

        # Clear theme files
        rm -rf ./wp-content/themes/ew-theme/node_modules
        rm -rf ./wp-content/themes/ew-theme/.scripts
        rm -rf ./wp-content/themes/ew-theme/gulp
        rm -rf ./wp-content/themes/ew-theme/webpack
        rm -rf ./wp-content/themes/ew-theme/assets/js
        rm -rf ./wp-content/themes/ew-theme/assets/styles
        rm -rf ./wp-content/themes/ew-theme/.babelrc
        rm -rf ./wp-content/themes/ew-theme/.editorconfig
        rm -rf ./wp-content/themes/ew-theme/.eslintignore
        rm -rf ./wp-content/themes/ew-theme/.eslintrc
        rm -rf ./wp-content/themes/ew-theme/gulpfile.js
        rm -rf ./wp-content/themes/ew-theme/README.md
        rm -rf ./wp-content/themes/ew-theme/yarn.lock
        rm -rf ./wp-content/themes/ew-theme/composer.json
        rm -rf ./wp-content/themes/ew-theme/package.json
        rm -rf ./wp-content/themes/ew-theme/composer.lock

        # Clear plugin files
        rm -rf ./wp-content/plugins/ewplugin/tests
        rm -rf ./wp-content/plugins/ewplugin/.phpcs.xml.dist
        rm -rf ./wp-content/plugins/ewplugin/.travis.yml
        rm -rf ./wp-content/plugins/ewplugin/phpunit.phar
        rm -rf ./wp-content/plugins/ewplugin/phpunit.xml.dist
        rm -rf ./wp-content/plugins/ewplugin/composer.json
        rm -rf ./wp-content/plugins/ewplugin/composer.lock

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'tar'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz'
      replaceExistingArchive: true
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz'
      artifact: 'supervisor.hr'
      publishLocation: 'pipeline'


